Issue-45
pndaproject/platform-console-frontend pull request #46
Opened 2017-11-08 09:36 UTC by deepamartin

**Problem Statement:**
ISSUE 45: Opentsdb component healthmetric information is not being displayed in console homepage.

**Analysis:**
There are no proper UI representation of information related to OpenTSDB. Presently, OpenTsdb has one URL on console homepage which redirects to another page. User cannot see the health status of opentsdb. 

**Change:**
Added UI represntation of opentsdb. It is a block like structure on homepage which has a color code which depends on health status of openTsdb. That block has three icon which are info, help and settings respectively.

2017-11-15 15:15 UTC, jeclarke requested changes
A couple of minor issues to fix up, I will go ahead and test this now anyway.

2017-11-15 15:15 UTC, jeclarke commented on console-frontend/help/topics.json
> +      "body": ["OpenTSDB is a scalable time series database that lets you store and serve massive amounts of time series data,without losing granularity.",
comma needed "data,without"

2017-11-15 15:15 UTC, jeclarke commented on console-frontend/js/controllers/MetricsListCtrl.js
> +          resolutionUrl =ConfigService.userInterfaceIndex[opentsdbIndex].split(",")[0];
space after = needed

2017-11-15 20:38 UTC, jeclarke commented
The testing was all good, it's working great. So just the couple of minor changes and I can merge this one.

2017-11-16 04:34 UTC, deepamartin commented
Hi, comma is already there in Topic.json for opentsdb in between "data" and "without": ["OpenTSDB is a scalable time series database that lets you store and serve massive amounts of time series **data,without** losing granularity."]

I added the space in MetricListCtrl.js. Please let me know if anything else is required.

2017-11-16 06:38 UTC, jeclarke commented
Sorry I meant a space needed after the comma.

2017-11-16 09:55 UTC, deepamartin commented
I added the space after the comma. Please let me know if anything else is required.

2017-11-16 10:06 UTC, jeclarke approved these changes

2017-11-16 10:08 UTC, merged